apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-host-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/e18680/dev/data/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-host-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi