apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
  labels:
    app: redisinsight
spec:
  type: LoadBalancer
  ports:
  - port: 8002
    targetPort: 5540
    protocol: TCP
  selector:
    app: redisinsight